/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/debug': RouteRecordInfo<'/debug', '/debug', Record<never, never>, Record<never, never>>,
    '/general_settings': RouteRecordInfo<'/general_settings', '/general_settings', Record<never, never>, Record<never, never>>,
    '/twitch_token_auth': RouteRecordInfo<'/twitch_token_auth', '/twitch_token_auth', Record<never, never>, Record<never, never>>,
    '/user_blacklist': RouteRecordInfo<'/user_blacklist', '/user_blacklist', Record<never, never>, Record<never, never>>,
    '/username_replacement': RouteRecordInfo<'/username_replacement', '/username_replacement', Record<never, never>, Record<never, never>>,
    '/voice_selector': RouteRecordInfo<'/voice_selector', '/voice_selector', Record<never, never>, Record<never, never>>,
    '/word_filter': RouteRecordInfo<'/word_filter', '/word_filter', Record<never, never>, Record<never, never>>,
    '/word_replacement': RouteRecordInfo<'/word_replacement', '/word_replacement', Record<never, never>, Record<never, never>>,
  }
}
